[project]
name = "info"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "zensical>=0.0.21",
    "playwright>=1.58.0",
    "pillow>=11.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.0",
]
