[project]
name = "info"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "zensical>=0.0.19",
    "playwright>=1.49.1",
    "pillow>=11.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.14",
]
